### ISSUE TITLE
Hey Seb!

### ISSUE THREAD

**Issue by lemarier** [se-bastiaan/se-bastiaan#1]
Hey Seb!

Long time no see!
Hope you are doing well, you seem to be done with school? So great!!!

I wonder if you still do Android dev?

I'm working on https://github.com/tauri-apps/tauri and I'm looking to bring it to android/android TV. 
We've done iOS already.

The main objective is to bring wry (our low-level interface) https://github.com/tauri-apps/wry to Android first, we use Rust but it's quite easy to get started I guess? We leverage the local webview instead of shipping a custom chromium.

It's something you would be interested to help with?

Thanks, bud!

**Comment by se-bastiaan** [comment]
@lemarier Just letting you know that I read this, probably have time to look into it this evening (and it's 14:00 now)

**Comment by lemarier** [comment]
Hey Seb!

I'm excited hahaaha!
If you have questions, reach me on discord @ https://discord.gg/SpmNs4S -- username: `lemarier#1302`

**Comment by lemarier** [comment]
Hey @se-bastiaan - If you are still interested it’ll be really great!

meanwhile, this is an article from cloudlfare about us;
https://css-tricks.com/how-i-built-a-cross-platform-desktop-application-with-svelte-redis-and-rust/

If you dont have much times, it’ll be really great if you can guide us tu bind  the android webview to rust
